<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>openai_loadbalancer</RootNamespace>
    <UserSecretsId>06475c31-d32a-4a5b-9c8d-0f290a8dbd75</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
	<ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.1" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Contracts/**" />
    <Content Remove="Contracts/**" />
    <None Remove="Contracts/**" />
    <ProjectReference Include="Contracts/openai-loadbalancer.Contracts.csproj" />
  </ItemGroup>

</Project>
